/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rbd.h"

bool_t
xdr_agenda (XDR *xdrs, agenda *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nome, 65,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->fone))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->endereco, 513,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
