/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rbd.h"
#include "rbd_cif.h"

void bd_agenda(char *host)
{
	char c;
	agenda *word;
	int option, i;
	/* Inicializando a agenda */
	handle = clnt_create (host, RBDPROG, RDBVERS, "tcp");
	inicializar();
	printf("Selecione a função que você deseja realizar:\n");
  	printf("1-Inserir\n2-Remover\n3-Buscar\n4-Sair\n");
  	c = getchar();
  	while(c != 4)
  	{
	    option = atoi(&c);
	    /* '\n' */
	    c = getchar();
	    switch(option)
	    {
	      case 1:
			word = (agenda*)malloc(sizeof(agenda));
			printf("Insira o nome: ");
			i = 0;
			c = getchar();
			while(c != '\n')
			{
				word->nome[i] = c;
				c = getchar();
				i++;
			}
			word->nome[i] = '\0';
			printf("Insira o telefone: ");
			scanf("%u", &word->fone);
			printf("Insira o endereço: ");
			i = 0;
			/* '\n' */
			c = getchar();
			c = getchar();
			while(c != '\n')
			{
				word->endereco[i] = c;
				c = getchar();
				i++;
			}
			word->endereco[i] = '\0';
			if(insere(word))
		  		printf("Inserção realizada com sucesso.\n");
			else
		  		printf("Ocorreu um erro na inserção.\n");
			free(word);
			break;
	      case 2:
			word = (agenda*)malloc(sizeof(agenda));
			printf("Insira o nome da pessoa a ser removida: ");
			i = 0;
			c = getchar();
			while(c != '\n')
			{
				word->nome[i] = c;
				c = getchar();
				i++;
			}
			word->nome[i] = '\0';
			if(remover(word))
			{
		  		printf("Remoção realizada com sucesso.\n");
			}
			else
		  		printf("Remoção falhou; o nome ou não existe ou ocorreu um erro na execução do programa. Verifique essas assertatitvas e se possível tente novamente.\n");
			free(word);
			break;
	      case 3:
			word = (agenda*)malloc(sizeof(agenda));
			printf("Insira o nome da pessoa a ser buscada: ");
			i = 0;
			c = getchar();
			while(c != '\n')
			{
				word->nome[i] = c;
				c = getchar();
				i++;
			}
			word->nome[i] = '\0';
			if(busca(word))
			{
		  		printf("Pessoa encontrada.\n");
		  		printf("Nome: %s\nTelefone: %u\nEndereço: %s\n", word->nome, word->fone, word->endereco);
		  	}
			else
		  		printf("Pessoa não encontrada. Verifique se ela realmente existe no banco de dados.\n");
			free(word);
			break;
	      case 4:
			clnt_destroy (handle);
			c = 4;
			break;
	      default:
			printf("Comando incorreto. Finalizando programa...\n");
			exit(-1);
	    }
	    if(c != 4)
	    {
	      printf("1-Inserir\n2-Remover\n3-Buscar\n4-Sair\n");
	      c = getchar();
	    }
  	}	
}

int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	bd_agenda(host);
exit (0);
}
