CFLAGS= -Wall -std=c99 -pedantic

all:	clean
	gcc blits.c lista.c -o blits $(CFLAGS)
	gcc blitsd.c listad.c -o blitsd $(CFLAGS)
	gcc blitsh.c hash.c -o blitsh $(CFLAGS)

clean:
	rm -rf checkin checkout pesquisar listarquartos

