-- phpMyAdmin SQL Dump
-- version 3.4.10.1deb1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Nov 17, 2014 at 12:52 PM
-- Server version: 5.5.40
-- PHP Version: 5.3.10-1ubuntu3.15

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `RepositorioQuestoes`
--

-- --------------------------------------------------------

--
-- Table structure for table `Materia`
--

CREATE TABLE IF NOT EXISTS `Materia` (
  `m_id` int(11) NOT NULL AUTO_INCREMENT,
  `nomeMateria` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `descricao` varchar(1024) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`m_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=11 ;

--
-- Dumping data for table `Materia`
--

INSERT INTO `Materia` (`m_id`, `nomeMateria`, `descricao`) VALUES
(1, 'Algoritmos e Programação', 'Capacitar o aluno a visualizar soluções computacionais para problemas através da aplicação dos conceitos da lógica de programação e dotá-los da capacidade de construção de programas em linguagem de alto nível. '),
(2, 'Compiladores', 'Um compilador é um programa de sistema que traduz um programa descrito em uma linguagem de alto nível para um programa equivalente em código de máquina para um processador. Em geral, um compilador não produz diretamente o código de máquina mas sim um programa em linguagem simbólica (assembly) semanticamente equivalente ao programa em linguagem de alto nível. O programa em linguagem simbólica é então traduzido para o programa em linguagem de máquina através de montadores. '),
(3, 'Redes de Computadores', 'Fornecer aos alunos conceitos fundamentais de Redes de Computadores e dos principais protocolos existentes. Discutir com o acadêmico o uso e o desenvolvimento de redes de computadores.'),
(4, 'Análise de Algoritmos', 'Desenvolver a capacidade de avaliar a complexidade e a qualidade dos algoritmos propostos para um determinado problema. Estudar os algoritmos básicos para as classes mais importantes de problemas tratados em computação. Compreender a importância da implementação e a sensibilidade do comportamento dos algoritmos. Conhecer as potencialidades e as limitações do conhecimento algorítmico atual.'),
(5, 'Arquitetura de Computadores', 'Ensinar ao aluno os conceitos básicos avançados de arquiteturas de computadores e capacitá-lo a compreender e avaliar as questões fundamentais do projeto da arquitetura de um computador, bem como se dá o funcionamento de um processador.'),
(6, 'Engenharia de Software', 'Engenharia de software é uma área da computação voltada à especificação, desenvolvimento e manutenção de sistemas de software, com aplicação de tecnologias e práticas de gerência de projetos e outras disciplinas, visando organização, produtividade e qualidade.'),
(7, 'Circuitos digitais ', 'O objetivo da disciplina é capacitar o aluno a compreender diferentes métodos de síntese de sistemas digitais complexos, ou seja, nesta disciplina estuda-se os princípios e técnicas que são comuns a todos os sistemas digitais, partindo da mais simples chave liga-desliga ao mais complexo computador.'),
(8, 'Fundamentos da Teoria da Computação', 'A disciplina Fundamentos da Teoria da Computação tem por objetivo introduzir o estudante de graduação em Ciência da Computação às linguagens formais, à teoria dos autômatos e à complexidade computacional, com ênfase nos dois primeiros tópicos. '),
(9, 'Linguagens Formais e Autômatos', 'A matéria tem como objetivo permitir com que os alunos compreendam as definições e propriedades de modelos matemáticos de computação, tais como, linguagens, autômatos e gramáticas.'),
(10, 'Sistemas Operacionais', 'O sistema operacional é uma camada de software que opera entre o hardware e os\nprogramas aplicativos voltados ao usuário final. O sistema operacional é uma estrutura\nde software ampla, muitas vezes complexa, que incorpora aspectos de baixo nível (como\ndrivers de dispositivos e gerência de memória física) e de alto nível (como programas\nutilitários e a própria interface gráfica). Os objetivos básicos de um sistema operacional podem ser sintetizados em duas\npalavras-chave: “abstração” e “gerência”.');

-- --------------------------------------------------------

--
-- Table structure for table `Questao`
--

CREATE TABLE IF NOT EXISTS `Questao` (
  `q_id` int(11) NOT NULL AUTO_INCREMENT,
  `m_id` int(11) NOT NULL,
  `dificuldade` varchar(15) COLLATE utf8_bin DEFAULT NULL,
  `enunciado` varchar(2048) COLLATE utf8_bin DEFAULT NULL,
  `alternativas` varchar(1024) COLLATE utf8_bin DEFAULT NULL,
  `resposta` varchar(1024) COLLATE utf8_bin DEFAULT NULL,
  `tipo_questao` varchar(45) COLLATE utf8_bin DEFAULT NULL,
  `ano` date DEFAULT NULL,
  `imagem` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `u_id` int(11) DEFAULT NULL,
  `texto_alt` varchar(1024) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`q_id`),
  KEY `m_id` (`m_id`),
  KEY `deletar` (`u_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=71 ;

--
-- Dumping data for table `Questao`
--

INSERT INTO `Questao` (`q_id`, `m_id`, `dificuldade`, `enunciado`, `alternativas`, `resposta`, `tipo_questao`, `ano`, `imagem`, `u_id`, `texto_alt`) VALUES
(1, 5, 'FÃ¡cil', 'Uma caracterÃ­stica de uma arquitetura RISC Ã©:', '(a) Uma arquitetura de alto risco pois o mercado de hardware evolui muito rapidamente\r\n\r\n(b) Possui um grande conjunto de instruÃ§Ãµes complexas\r\n\r\n(c) A arquitetura Ã© constituÃ­da de milhares de processadores\r\n\r\n(d) Possui um pequeno conjunto de instruÃ§Ãµes simples\r\n\r\n(e) O processador Ã© formado por vÃ¡lvulas e transistores', '(d) Possui um pequeno conjunto de instruÃ§Ãµes simples', 'Poscomp', '2002-09-10', NULL, 4, 'NÃ£o hÃ¡ imagem para essa questÃ£o.'),
(2, 5, 'FÃ¡cil', 'Sistemas de memÃ³ria de dois nÃ­veis, na forma como acontece em sistemas com memÃ³ria cache, baseiam-se no princÃ­pio', '(a) da Localidade de ReferÃªncia, que afirma que as referÃªncias Ã  memÃ³ria tendem a se agrupar\r\n\r\n(b) da Localidade de ReferÃªncia, que necessita que as instruÃ§Ãµes de acesso Ã  memÃ³ria utilizem endereÃ§amento indireto Ã  memÃ³ria\r\n\r\n(c) do Pipeline, que faz com que a busca de um dado na memÃ³ria seja quebrada em uma sequÃªncia de passos elementares \r\n\r\n(d) do Pipeline, que afirma que as referÃªncias Ã  memÃ³ria tendem a estar distribuÃ­das de maneira uniforme\r\n\r\n(e) da Lei de Moore, que prevÃª que a complexidade dos algoritmos duplique a cada 18 meses', '(a) da Localidade de ReferÃªncia, que afirma que as referÃªncias Ã  memÃ³ria tendem a se agrupar', 'Concurso', '2014-07-13', NULL, 4, ''),
(3, 5, 'FÃ¡cil', 'Julgue os itens a seguir, relativos Ã  organizaÃ§Ã£o dos computadores modernos.', 'I - Na organizaÃ§Ã£o de um sistema computacional em que se utilizam dispositivos de entrada e saÃ­da, uma das funÃ§Ãµes da interface controladora Ã© a de seletor e decodificador de endereÃ§os.\r\n\r\nII - Em uma arquitetura computacional, o tamanho da instruÃ§Ã£o, em bits, influencia diretamente o desenvolvimento da implementaÃ§Ã£o e a organizaÃ§Ã£o dos bancos registradores.\r\n\r\nIII - Mediante a unidade lÃ³gica aritmÃ©tica (ULA), realizam-se operaÃ§Ãµes Ãºnica e exclusivamente entre os conteÃºdos de registradores, independentemente da arquitetura e da organizaÃ§Ã£o computacional utilizada.\r\n\r\nIV - Em uma arquitetura computacional, o modo de endereÃ§amento em bytes exige que o conteÃºdo de dados alocados nos registradores seja, obrigatoriamente, mÃºltiplo de 8 bits.', 'I - Verdadeiro, II - Falso, III - Falso, IV - Falso', 'Concurso', '2014-06-10', NULL, 4, ''),
(5, 5, 'MÃ©dia', 'Seja um programa P que executa n instruÃ§Ãµes.', '(a) P Ã© executado no processador MIPS simples ("monociclo"). \n     Quantos ciclos do clock (do processador simples) P levarÃ¡ para executar atÃ© o fim? \n\n(b) P Ã© executado no processador MIPS com pipeline de 5 estÃ¡gios.\n     Suponha que nÃ£o hÃ¡ conflitos entre as instruÃ§Ãµes.\n     Quantos ciclos do clock (do processador com pipeline) P levarÃ¡ para executar atÃ© o fim?', '(a) n ciclos do clock, (b) n+4 ciclos do clock', 'AcadÃªmica', '2013-11-14', '/var/www/trabalho_progweb/misc/imagens/questao/pipeline20141115101225418692928.png', 4, 'Uma imagem representando um pipeline (simples) de um processador.'),
(6, 5, 'FÃ¡cil', 'O que Ã© um barramento, em termos de conexÃµes entre dispositivos de entrada e saÃ­da?', '', 'O barramento Ã© o principal meio de transmissÃ£o de dados entre recursos, e permite com que novos dispositivos de entrada e saÃ­da possam ser adicionados graÃ§as ao seu padrÃ£o de conexÃ£o. Entretanto, ele Ã© o gargalo de um sistema, pois seu comprimento e suporte a dispositivos com tempo de acesso e taxas de tranferÃªncias de dados Ã© muito diferente, o que torna o projeto desse mais complexo.', 'AcadÃªmica', '2013-11-24', NULL, 4, 'NÃ£o hÃ¡ imagem.'),
(7, 4, 'MÃ©dia', 'Considere o algoritmo da busca sequencial de um elemento em um conjunto com n elementos. A expressÃ£o que representa o tempo mÃ©dio de execuÃ§Ã£o desse algoritmo para uma busca bem sucedida Ã© (nota: a base logarÃ­tmica das alternativas Ã© 2):', '(a) nÂ²\r\n\r\n(b) n(n-1)/2\r\n\r\n(c) log n\r\n\r\n(d) (n-1)/2\r\n\r\n(e) n log n', '(d) (n-1)/2', 'Poscomp', '2002-09-10', NULL, 1, ''),
(8, 4, 'MÃ©dia', 'Qual dos algoritmos de ordenaÃ§Ã£o abaixo possuem tempo no pior caso e tempo mÃ©dio de execuÃ§Ã£o proporcional a O(n log n):', '(a) Bubble sort e Quick sort\r\n\r\n(b) Quick sort e Merge sort\r\n\r\n(c) Merge sort e Bubble sort\r\n\r\n(d) Heap sort e Selection sort\r\n\r\n(e) Merge sort e Heap sort', '(e) Merge sort e Heap sort', 'Poscomp', '2002-09-10', NULL, 1, 'Sem imagem.'),
(9, 4, 'FÃ¡cil', 'Professor Mac Sperto propÃ´s o seguinte algoritmo de ordenaÃ§Ã£o, chamado de Super Merge, similar ao Merge Sort: divida o vetor em 4 partes do mesmo tamanho (ao invÃ©s de 2, como Ã© feito no Merge Sort). Ordene recursivamente cada uma das partes e depois intercale-as por um procedimento semelhante ao procedimento de intercalaÃ§Ã£o do Merge Sort. Qual das alternativas abaixo Ã© verdadeira?\r\n\r\n', '(a) Super Merge nÃ£o estÃ¡ correto. NÃ£o Ã© possÃ­vel ordenar quebrando o vetor em 4 partes\r\n\r\n(b) Super Merge estÃ¡ correto, mas consome tempo O(Merge Sort)\r\n\r\n(c) Super Merge estÃ¡ correto, mas consome tempo maior que O(Merge Sort)\r\n\r\n(d) Super Merge estÃ¡ correto, mas consome tempo menos que O(Merge Sort)\r\n\r\n(e) Nenhuma das afirmaÃ§Ãµes acima estÃ¡ correta ', '(b) Super Merge estÃ¡ correto, mas consome tempo O(Merge Sort)', 'Poscomp', '2002-09-10', NULL, 1, ''),
(10, 10, 'MÃ©dia', 'No que diz respeito as vantagens da arquitetura de micro-nÃºcleo para sistemas operacionais em relaÃ§Ã£o a arquiteturas de nÃºcleo monolÃ­tico, quais das seguintes afirmaÃ§Ãµes sÃ£o verdadeiras? \r\n\r\nI - A arquitetura de micro-nÃºcleo facilita a depuraÃ§Ã£o do SO.\r\n\r\nII - A arquitetura de micro-nÃºcleo permite um nÃºmero menor de mudanÃ§as de contexto.\r\n\r\nIII - A arquitetura de micro-nÃºcleo facilita a reconfiguraÃ§Ã£o de serviÃ§os do SO pois a maioria deles reside em espaÃ§o de usuÃ¡rio.', '(a) Apenas I\r\n\r\n(b) II e III\r\n\r\n(c) I e III\r\n\r\n(d) I e II\r\n\r\n(e) Todas sÃ£o verdadeiras', '(c) I e III', 'Poscomp', '2002-09-10', NULL, 1, ''),
(11, 10, 'MÃ©dia', 'Considere um sistema distribuÃ­do onde cada nÃ³ precisa obter um bloqueio (lock) antes de acessar qualquer serviÃ§o no sistema. Qual das estratÃ©gias a seguir nÃ£o seria eficaz para evitar impasses (deadlocks)?', '(a) Associar prioridades aos nÃ³s e criar filas de prioridades para cada serviÃ§o\r\n\r\n(b) Numerar os serviÃ§os e exigir que cada nÃ³ solicite os bloqueios dos serviÃ§os em ordem crescente\r\n\r\n(c) Instalar um serviÃ§o de detecÃ§Ã£o de impasses no sistema distribuÃ­do e reiniciar os nÃ³s que atinjam um impasse\r\n\r\n(d) Fazer com que cada nÃ³ reinicie sua execuÃ§Ã£o se um pedido de bloqueio nÃ£o Ã© concedido apÃ³s um longo tempo de espera. O pedido de bloqueio Ã© reenviado apÃ³s um tempo aleatÃ³rio\r\n\r\n(e) ForÃ§ar cada nÃ³ a obter todos os bloqueios de que necessita no inÃ­cio de sua execuÃ§Ã£o e reiniciar a execuÃ§Ã£o se algum bloqueio nÃ£o Ã© concedido ', '(a) Associar prioridades aos nÃ³s e criar filas de prioridades para cada serviÃ§o', 'Poscomp', '2002-09-10', NULL, 1, ''),
(14, 9, 'MÃ©dia', 'Assinale quantas sequÃªncias de caracteres a seguir sÃ£o reconhecidas pelo autÃ´mato finito abaixo. As quatro sequÃªncias de caracteres (separadas por vÃ­rgulas) sÃ£o: 0, -567, -89.5, -3e3.', '(a) 0\r\n\r\n(b) 1\r\n\r\n(c) 2\r\n\r\n(d) 3\r\n\r\n(e) 4', '(c) 2', 'Poscomp', '2002-09-10', '/var/www/trabalho_progweb/misc/imagens/questao/lfa201411151140351559204827.png', 1, 'Uma imagem de uma mÃ¡quina de estados.'),
(16, 2, 'DifÃ­cil', 'Considere as seguintes afirmaÃ§Ãµes sobre as linguagens usadas para anÃ¡lise sintÃ¡tica: \r\n\r\nI - Os analisadores LL(1) aceitam linguagens com produÃ§Ãµes que apresentem recursÃµes a esquerda.\r\n\r\nII - Os analisadores LR(1) reconhecem uma classe de linguagens maior que os analisadores LALR(1).\r\n\r\nIII - Os analisadores SLR(1) reconhecem uma classe de linguagens menor que os analisadores LR(0).\r\n\r\nSelecione a afirmativa correta.', '(a) As afirmaÃ§Ãµes I e II sÃ£o verdadeiras\r\n\r\n(b) As afirmaÃ§Ãµes I e III sÃ£o verdadeiras\r\n\r\n(c) Apenas a afirmativa III Ã© verdadeira\r\n\r\n(d) As afirmaÃ§Ãµes II e III sÃ£o verdadeiras\r\n\r\n(e) As afirmaÃ§Ãµes I e III sÃ£o falsas', '(b) As afirmaÃ§Ãµes I e III sÃ£o verdadeiras', 'Concurso', '2012-05-10', NULL, 6, ''),
(17, 2, 'FÃ¡cil', 'Seja a seguinte linguagem, onde epsilon representa a sentenÃ§a vazia:', 'Qual o conjunto de terminais que podem comeÃ§ar sentenÃ§as derivadas de S ? \r\n\r\n(a) {a, c, g}\r\n\r\n(b) {a, b, f, c, g}\r\n\r\n(c) {a, b, f, c, g, h, i}\r\n\r\n(d) {a, c, g, h, i}\r\n\r\n(e) {a, b, f}', '(c) {a, b, f, c, g, h, i}', 'AcadÃªmica', '2012-02-13', '/var/www/trabalho_progweb/misc/imagens/questao/comp20141115121430862280070.png', 6, 'Imagem de uma linguagem.'),
(18, 2, 'MÃ©dia', 'O esquema de traduÃ§Ã£o dirigida por sintaxe que segue traduz uma linguagem com terminais a, b, c e d em uma linguagem cujos terminais sÃ£o 1, \r\n2, 3, 4, 5, 6. Usando um parser bottom-up que executa as aÃ§Ãµes entre parÃªnteses imediatamente apÃ³s reduzir a regra correspondente, qual o resultado da traduÃ§Ã£o de \r\nâ€œaaadbcâ€:', '(a) 1313132546\r\n\r\n(b) 1113332546\r\n\r\n(c) 3336452111\r\n\r\n(d) 6452111333\r\n\r\n(e) 2546131313', '(b) 1113332546', 'AcadÃªmica', '2012-02-13', '/var/www/trabalho_progweb/misc/imagens/questao/comp2201411151219001066763633.png', 6, 'Um esquema de traduÃ§Ã£o dirigido por sintaxe.'),
(19, 2, 'MÃ©dia', 'Analise as seguintes afirmativas sobre os parsers descendentes recursivos. \r\n\r\nI - SÃ£o parsers fÃ¡ceis de implementar para linguagens cuidadosamente projetadas, porÃ©m geralmente exigem transformaÃ§Ãµes em gramÃ¡ticas originalmente\r\napresentadas em BNF. \r\n\r\nII - Um dos principais problemas desse tipo de parser Ã© a necessidade de retrocesso nas alternativas, o que pode ser resolvido com o uso de um parser recursivo\r\npreditivo. \r\n\r\nIII - Para evitar os problemas do parser descendente recursivo, podemos realizar a anÃ¡lise TOP-DOWN usando um parser preditivo nÃ£o recursivo, ou parser preditivo tabular. O parser preditivo tabular usa uma tabela baseada nos conjuntos FIRST e FOLLOW para decidir qual produÃ§Ã£o aplicar Ã  entrada.', 'A anÃ¡lise permite concluir que \r\n\r\n(a) apenas a afirmativa I estÃ¡ correta.\r\n\r\n(b) apenas a afirmativa II estÃ¡ correta.\r\n\r\n(c) apenas a afirmativa III estÃ¡ correta.\r\n\r\n(d) apenas as afirmativas I, II estÃ£o corretas.\r\n\r\n(e) as trÃªs afirmativas estÃ£o corretas.', '(e) as trÃªs afirmativas estÃ£o corretas.', 'Poscomp', '2012-02-13', NULL, 6, 'Nenhuma imagem.'),
(20, 2, 'MÃ©dia', 'Analise as seguintes afirmativas sobre a fase de anÃ¡lise (Front-End) de um compilador. \r\n\r\nI - O uso de uma variÃ¡vel de ponto flutuante para indexar um vetor causa um erro geralmente detectado na anÃ¡lise semÃ¢ntica. \r\n\r\nII - ParÃªnteses desbalanceados sÃ£o um erro geralmente detectado pela anÃ¡lise lÃ©xica jÃ¡ que essa fase lÃª o arquivo fonte e o traduz para um a sequÃªncia de sÃ­mbolos lÃ©xicos, ou tokens. \r\n\r\nIII - Para a anÃ¡lise sintÃ¡tica TOP-DOWN usando o mÃ©todo de empilhar e reduzir, Ã© necessÃ¡rio reescrever a gramÃ¡tica eliminando toda recursividade Ã  esquerda. ', 'A anÃ¡lise permite concluir que \r\n\r\n(a) todas as afirmativas sÃ£o incorretas.\r\n\r\n(b) apenas a afirmativa II Ã© incorreta.\r\n\r\n(c) apenas as afirmativas I e II sÃ£o incorretas.\r\n\r\n(d) apenas as afirmativas I e III sÃ£o incorretas.\r\n\r\n(e) apenas as afirmativas II e III sÃ£o incorretas.', '(b) apenas a afirmativa II Ã© incorreta.', 'Concurso', '2012-02-13', NULL, 6, ''),
(21, 4, 'MÃ©dia', 'Considere um problema em que sÃ£o dados 5 objetos com os seguintes pesos e valores:\r\n\r\npesos: (W1, W2, W3, W4, W5) = (6, 10, 9, 5, 12)\r\nvalores: (P1, P2, P3, P4, P5) = (8, 5, 10, 15, 7)\r\n\r\nAlÃ©m disso, Ã© dada uma mochila que suporta atÃ© 30 unidades de peso, para transportar os objetos. O objetivo do problema Ã© preencher a mochila de tal forma que o valor total dos objetos a serem transportados seja o maior possÃ­vel, mas sem exceder o limite de peso suportado pela mochila. Assuma que Ã© permitido colocar fraÃ§Ã£o de um objeto na mochila. Qual das seguintes alternativas corresponde ao valor mÃ¡ximo obtido no preenchimento da mochila:', '(a) 12.2\r\n\r\n(b) 21.5\r\n\r\n(c) 30.34\r\n\r\n(d) 38.83\r\n\r\n(e) 43.1', '(d) 38.83', 'AcadÃªmica', '2012-02-13', NULL, 4, ''),
(25, 6, 'FÃ¡cil', 'Com relaÃ§Ã£o Ã  engenharia de requisitos, afirme verdadeiro (V) ou falso (F) para os seguintes itens:', 'I - A linguagem natural estruturada, em que Ã© admitida a utilizaÃ§Ã£o de construÃ§Ãµes de linguagem de programaÃ§Ã£o, Ã© uma tÃ©cnica de especificaÃ§Ã£o de requisitos.\r\n\r\nII - A etnografia auxilia na descoberta de requisitos implÃ­citos do sistema ao se observar a forma como um trabalho Ã© executado, em vez de se verificar como os processos sÃ£o definidos pela organizaÃ§Ã£o.\r\n\r\nIII - O gerenciamento de requisitos Ã© planejado durante o processo de elicitaÃ§Ã£o de requisitos e iniciado quando se torna disponÃ­vel a primeira versÃ£o do documento de requisitos aprovada pelos stakeholders.', 'I - Falso, II - Falso, III - Verdadeiro', 'AcadÃªmica', '2014-09-20', NULL, 1, 'NÃ£o hÃ¡ imagem.'),
(26, 6, 'DifÃ­cil', 'No que diz respeito Ã  engenharia de testes, julgue os itens subsecutivos como verdadeiros (V) ou falsos (F).', 'I - A adoÃ§Ã£o da estratÃ©gia bottom-up nos testes de integraÃ§Ã£o torna desnecessÃ¡ria a utilizaÃ§Ã£o de stubs. \r\n\r\nII - A realizaÃ§Ã£o de testes de carga Ã© importante para os sistemas distribuÃ­dos, pois permite a identificaÃ§Ã£o do ponto de degradaÃ§Ã£o desses sistemas, o que possibilita a criaÃ§Ã£o de controles de rejeiÃ§Ã£o de operaÃ§Ãµes a partir desse ponto.\r\n\r\nIII - A medida de complexidade ciclomÃ¡tica Ã© obtida pela contagem de estruturas de seleÃ§Ã£o e repetiÃ§Ã£o ou pela contagem do nÃºmero de regiÃµes do grafo de fluxo, tendo a segunda tÃ©cnica menor precisÃ£o que a primeira.', 'I - Falso, II - Verdadeiro, III - Falso', 'Concurso', '2012-07-20', '', 6, ''),
(27, 6, 'FÃ¡cil', 'Considere as seguintes afirmativas sobre Teste de Software.\r\n\r\nI - A atividade de teste Ã© considerada uma atividade dinÃ¢mica, pois implica na\r\nexecuÃ§Ã£o do cÃ³digo.\r\nII - As etapas que usualmente compreendem a atividade de teste sÃ£o: planejamento,\r\nprojeto de casos de teste, execuÃ§Ã£o dos casos de teste e anÃ¡lise dos resultados.\r\nIII - A atividade de teste deve ser iniciada na fase de codificaÃ§Ã£o.\r\nIV - Testar e depurar um programa sÃ£o atividades que se confundem.', 'Assinale a alternativa CORRETA:\r\n\r\n(a) Somente as afirmativas I e II sÃ£o verdadeiras.\r\n\r\n(b) Somente as afirmativas II e III sÃ£o verdadeiras.\r\n\r\n(c) Somente as afirmativas I, III e IV sÃ£o verdadeiras.\r\n\r\n(d) As afirmativas I, II e IV sÃ£o falsas.\r\n\r\n(e) Todas as afirmativas sÃ£o verdadeiras.', '(a) Somente as afirmativas I e II sÃ£o verdadeiras.', 'AcadÃªmica', '2011-05-20', '', 6, ''),
(28, 6, 'MÃ©dia', 'Considere as seguintes afirmativas sobre Qualidade de Software:\r\n\r\nI - A qualidade de software enfatiza pontos como: requisitos explÃ­citos, requisitos\r\nimplÃ­citos e normas ou padrÃµes de desenvolvimento de software.\r\nII - A qualidade de software pode ser avaliada sob a perspectiva de qualidade do\r\nproduto de software. Esta avaliaÃ§Ã£o ocorre com base nos padrÃµes de\r\ndesenvolvimento do software.\r\nIII - Um dos fundamentos bÃ¡sicos da gerÃªncia da qualidade Ã© a padronizaÃ§Ã£o, que\r\npode ser aplicada em diversos nÃ­veis: na documentaÃ§Ã£o, no cÃ³digo e no processo.\r\nIV - A gerÃªncia de qualidade do projeto consegue uma melhor visibilidade do projeto\r\npor meio da rastreabilidade de requisitos de software.', 'Assinale a alternativa CORRETA:\r\n\r\n(a) Somente as afirmativas I e II sÃ£o verdadeiras.\r\n\r\n(b) Somente as afirmativas II e III sÃ£o verdadeiras.\r\n\r\n(c) Somente as afirmativas I, III e IV sÃ£o verdadeiras.\r\n\r\n(d) As afirmativas I, II e IV sÃ£o falsas.\r\n\r\n(e) Todas as afirmativas sÃ£o verdadeiras.', '(c) Somente as afirmativas I, III e IV sÃ£o verdadeiras.', 'AcadÃªmica', '2011-05-20', '', 6, ''),
(29, 6, 'DifÃ­cil', 'Na maioria dos projetos de software, mudanÃ§as sÃ£o inevitÃ¡veis. Quanto mais tarde forem identificadas, maior o custo de incorporÃ¡-las ao projeto. Alguns tipos de\r\nmudanÃ§a, entretanto, sÃ£o mais caros que outros. O grÃ¡fico a seguir apresenta quatro categorias de grupos de mudanÃ§as, cujas curvas de custo estÃ£o identificadas pelos algarismos I, II, III e IV. Associe essas curvas com o grupo de mudanÃ§a correspondente.', 'Grupos de mudanÃ§a:\r\nI - MudanÃ§a na arquitetura do software.\r\nII - MudanÃ§a no projeto e na implementaÃ§Ã£o.\r\nIII - ReduÃ§Ã£o de Escopo.\r\nIV - MudanÃ§a nas regras de negÃ³cio.\r\n\r\nA associaÃ§Ã£o correta, de cima para baixo, Ã©\r\n\r\n(a) III, IV, I, II\r\n\r\n(b) III, II, IV, I\r\n\r\n(c) III, II, I, IV\r\n\r\n(d) II, III, IV, I\r\n\r\n(e) I, IV, III, II', '(e) I, IV, III, II', 'Concurso', '2010-09-09', '/var/www/trabalho_progweb/misc/imagens/questao/engsoft201411151353521716056616.png', 6, 'GrÃ¡fico de custo de mudanÃ§as.'),
(30, 8, 'FÃ¡cil', 'Considerando a forma normal conjuntiva (FNC) e a forma normal disjuntiva (FND) na lÃ³gica proposicional clÃ¡ssica, avalie as afirmaÃ§Ãµes a seguir:\r\n\r\nI - A fÃ³rmula Â¬p âˆ¨ r estÃ¡ na FNC e na FND.\r\nII - A fÃ³rmula Â¬p ^ (r âˆ¨ q) estÃ¡ na FNC.\r\nIII - Uma fÃ³rmula na FNC Ã© uma conjunÃ§Ã£o de clÃ¡usulas.\r\nIV - Uma fÃ³rmula na FND Ã© uma disjunÃ§Ã£o dual de clÃ¡usulas.\r\nV - Uma clÃ¡usula Ã© uma conjunÃ§Ã£o de literais.\r\nVI - A fÃ³rmula ( Â¬p âˆ¨ q âˆ¨ r) ^ (Â¬q âˆ¨ t) ^ (Â¬r âˆ¨ s âˆ¨ a) estÃ¡ na FNC.\r\nVII -  Para toda fÃ³rmula da lÃ³gica proposicional clÃ¡ssica A, existe uma fÃ³rmula B na FND que Ã© equivalente a A.', 'Ã‰ correto apenas o que se afirma em:\r\n\r\n(a) I, II, III, V e VI\r\n\r\n(b) I, II, III e VII\r\n\r\n(c) I, II, V, VI e VII\r\n\r\n(d) I, II, III, VI e VII\r\n\r\n(e) I, III, IV, V e VI', '(d) I, II, III, VI e VII', 'AcadÃªmica', '2012-05-10', NULL, 1, 'Imagem nÃ£o inserida.'),
(31, 8, 'DifÃ­cil', 'A proposiÃ§Ã£o Â¬ (P ^ Q) â†’ (Â¬Q âˆ¨ P), assumindo que a sequÃªncia de valores de P Ã© {V,V,F,F} e a de Q Ã© {V,F,V,F}, tem os valores:', '(a) {F,F,F,F}\r\n\r\n(b) {V,V,V,V}\r\n\r\n(c) {F,F,V,V}\r\n\r\n(d) {V,V,F,V}\r\n\r\n(e) {V,F,V,F}', '(d) {V,V,F,V}', 'AcadÃªmica', '2012-02-13', NULL, 1, ''),
(32, 10, 'FÃ¡cil', 'Considere as seguintes definiÃ§Ãµes de operaÃ§Ãµes em semÃ¡foros:\r\n\r\nI - wait(s): a tarefa espera atÃ© que o semÃ¡foro seja verdadeiro\r\nII - down(s): a tarefa decrementa o semÃ¡foro e pode ficar bloqueada se este jÃ¡ estiver\r\nocupado.\r\nIII - notify(s): a tarefa avisa que hÃ¡ um novo valor disponÃ­vel no buffer do semÃ¡foro e\r\nacorda a primeira tarefa que estiver aguardando por ele.\r\nIV - signal(s): a tarefa incrementa o semÃ¡foro e acorda as demais tarefas que estiverem\r\naguardando por ele.\r\nV - up(s): a tarefa incrementa o semÃ¡foro e pode liberar uma outra tarefa que esteja\r\naguardando por ele.\r\nVI - broadcast(s): a tarefa acorda as demais tarefas que estiverem aguardando no\r\nsemÃ¡foro', 'As duas operaÃ§Ãµes bÃ¡sicas definidas por Dijkstra para os semÃ¡foros sÃ£o:\r\n\r\n(a) I e III\r\n\r\n(b) I e VI\r\n\r\n(c) II e VI\r\n\r\n(d) I e IV\r\n\r\n(e) II e V', '(e) II e V', 'AcadÃªmica', '2012-06-20', NULL, 6, ''),
(33, 10, 'DifÃ­cil', 'Considere as duas threads cujos pseudo-cÃ³digos sÃ£o descritos a seguir. Os semÃ¡foros s1 e s2 sÃ£o inicializados em zero (0):', ' A saÃ­da gerada na tela pela execuÃ§Ã£o concorrente das duas threads Ã©:\r\n\r\n(a) AXBY ou AXYB\r\n\r\n(b)XABY ou XAYB\r\n\r\n(c)XABY ou AXBY\r\n\r\n(d)XAYB ou AXYB\r\n\r\n(e)nenhuma das anteriores.', '(b)XABY ou XAYB', 'Concurso', '2012-07-20', '/var/www/trabalho_progweb/misc/imagens/questao/threads20141115142420173879428.png', 6, 'Pseudo-cÃ³digos de threads.'),
(34, 10, 'MÃ©dia', 'Considere um banco de memÃ³ria com os seguintes â€œburacosâ€ nÃ£o-contÃ­guos: ', 'Nesse banco de memÃ³ria devem ser alocadas Ã¡reas de 5MB, 10MB e 2MB, nesta ordem, usando os algoritmos de alocaÃ§Ã£o First-fit, Best-fit ou Worst-fit. Indique a alternativa correta:\r\n\r\n(a) Se usarmos Best-fit, o tamanho final do buraco B4 serÃ¡ de 6 Mbytes.\r\n\r\n(b) Se usarmos Worst-fit, o tamanho final do buraco B4 serÃ¡ de 15 Mbytes.\r\n\r\n(c) Se usarmos First-fit, o tamanho final do buraco B4 serÃ¡ de 24 Mbytes.\r\n\r\n(d)Se usarmos Best-fit, o tamanho final do buraco B5 serÃ¡ de 7 Mbytes.\r\n\r\n(e)Se usarmos Worst-fit, o tamanho final do buraco B4 serÃ¡ de 9 Mbytes.', '(b) Se usarmos Worst-fit, o tamanho final do buraco B4 serÃ¡ de 15 Mbytes.', 'Poscomp', '2012-05-10', '/var/www/trabalho_progweb/misc/imagens/questao/algoritmoalocacao201411151427501016900054.png', 6, 'Imagem de buracos nÃ£o contÃ­guos de memÃ³ria.'),
(35, 4, 'MÃ©dia', 'A respeito de algoritmos de ordenaÃ§Ã£o, Ã© INCORRETO afirmar:', '(a) Embora no caso mÃ©dio o famoso algoritmo Quicksort ordene um conjunto de dados em tempo O(n log n), no pior caso ele pode se sair tÃ£o mal quanto um algoritmo ingÃªnuo como o mÃ©todo da bolha, que tem complexidade de tempo O(nÂ²)\r\n\r\n(b) NÃ£o existe um algoritmo que ordene um conjunto de n nÃºmeros inteiros que execute em tempo O(log n)\r\n\r\n(c) Independente da entrada, o algoritmo Mergesort tem a mesma complexidade de tempo tanto para o melhor caso, o caso mÃ©dio e o pior caso\r\n\r\n(d) O algoritmo Insertion Sort, embora nÃ£o seja considerado eficiente, tem bom desempenho e tem complexidade de tempo O(n) se executado sobre um conjunto de dados que jÃ¡ estÃ¡ ordenado\r\n\r\n(e) A complexidade no caso mÃ©dio do algoritmo Selection Sort Ã© O(n log n)', '(e) A complexidade no caso mÃ©dio do algoritmo Ã© Selection Sort O(n log n)', 'AcadÃªmica', '2012-05-10', '', 11, ''),
(38, 6, 'MÃ©dia', 'Considere as seguintes afirmativas sobre Requisitos de Software:\r\n\r\nI - Requisitos Funcionais descrevem as funÃ§Ãµes que o software deverÃ¡ executar.\r\nII - Requisitos Funcionais nÃ£o sÃ£o rastreÃ¡veis, ou seja, nÃ£o Ã© possÃ­vel identificar o\r\ncÃ³digo fonte relacionado a um requisito funcional.\r\nIII - Requisitos NÃ£o-Funcionais descrevem as aÃ§Ãµes realizadas para cada entrada do\r\nsistema, ou seja, Ã© aquilo que descreve o que deve ser feito pelo sistema.', 'Assinale a alternativa CORRETA:\r\n\r\n(a) Apenas a afirmativa I Ã© verdadeira.\r\n\r\n(b) Apenas as afirmativas I e III sÃ£o verdadeiras.\r\n\r\n(c) Apenas a afirmativa II Ã© verdadeira.\r\n\r\n(d) Apenas as afirmativas II e III sÃ£o verdadeiras.\r\n\r\n(e) Todas as afirmativas sÃ£o verdadeiras.', '(a) Apenas a afirmativa I Ã© verdadeira.', 'Concurso', '2012-02-13', NULL, 11, ''),
(39, 6, 'FÃ¡cil', 'Segundo as caracterÃ­sticas da Unified Modeling Language (UML) 2.0, no Diagrama de Classes a seguir quais sÃ£o os atributos de uma instÃ¢ncia da classe D:', '(a) a0, b0, c0, d0, e0\r\n\r\n(b) d0\r\n\r\n(c) a0, b0, d0, e0\r\n\r\n(d) d0, e0\r\n\r\n(e) a0, d0, e0', '(b) d0', 'AcadÃªmica', '2012-05-10', '/var/www/trabalho_progweb/misc/imagens/questao/engs201411151443461975684380.png', 11, 'Imagem de um diagrama de classes.'),
(40, 6, 'MÃ©dia', 'Considerando as seguintes afirmativas sobre a Unified Modeling Language (UML) 2.0, Ã© correto afirmar que no Diagrama de Casos de Uso a seguir:', 'I - O caso de uso â€œValidar o usuÃ¡rioâ€ poderÃ¡ ser executado ou nÃ£o.\r\nII - O caso de uso â€œEnviar via SEDEXâ€ poderÃ¡ ser executado ou nÃ£o.\r\nIII - O caso de uso â€œValidar o usuÃ¡rioâ€ sempre Ã© executado.\r\nIV - O caso de uso â€œEnviar via SEDEXâ€ sempre Ã© executado.\r\n\r\nAssinale a alternativa CORRETA:\r\n\r\n(a) Apenas a afirmativa I Ã© verdadeira\r\n\r\n(b) Apenas a afirmativa II Ã© verdadeira\r\n\r\n(c) Apenas a afirmativa III Ã© verdadeira\r\n\r\n(d) Apenas as afirmativas I e IV sÃ£o verdadeiras\r\n\r\n(e) Apenas as afirmativas II e III sÃ£o verdadeiras', '(e) Apenas as afirmativas II e III sÃ£o verdadeiras', 'Concurso', '2012-05-10', '/var/www/trabalho_progweb/misc/imagens/questao/usecase201411151446051237522150.png', 11, 'Imagem de um diagrama de casos de uso.'),
(41, 7, 'FÃ¡cil', 'Na Ãlgebra Booleana:\r\n', '(a) Os dÃ­gitos sÃ£o octais, de 0 a 7\r\n\r\n(b) Os dÃ­gitos sÃ£o binÃ¡rios 0 e 1\r\n\r\n(c) HÃ¡ dez valores motivados pelos dez dedos do ser humano \r\n\r\n(d) Os dÃ­gitos sÃ£o alfanumÃ©ricos que podem ser representados por um byte\r\n\r\n(e) Os dÃ­gitos sÃ£o hexadecimais de 0 a 15', '(b) Os dÃ­gitos sÃ£o binÃ¡rios 0 e 1', 'Poscomp', '2002-09-10', NULL, 11, ''),
(42, 7, 'FÃ¡cil', 'Considere o circuito abaixo, implementado com duas portas NAND.', 'Qual das seguintes portas equivale a este circuito?\r\n\r\n(a) NOT\r\n\r\n(b) OR\r\n\r\n(c) AND\r\n\r\n(d) XOR \r\n\r\n(e) NOR', '(c) AND', 'Concurso', '2002-09-10', '/var/www/trabalho_progweb/misc/imagens/questao/isd20141115145710799077613.png', 11, 'Uma imagem de um circuito.'),
(43, 1, 'FÃ¡cil', 'Suponha que T seja uma Ã¡rvore AVL inicialmente vazia, e considere a inserÃ§Ã£o dos elementos 10, 20, 30, 5, 15, 2 em T, nesta ordem. Qual das sequÃªncias abaixo corresponde a um percurso de T em prÃ©-ordem:\r\n\r\n', '(a) 10, 5, 2, 20, 15, 30\r\n\r\n(b) 20, 10, 5, 2, 15, 30\r\n\r\n(c) 2, 5, 10, 15, 5, 2\r\n\r\n(d) 30, 20, 15, 10, 5, 2\r\n\r\n(e) 15, 10, 5, 2, 20 ,30', '(a) 10, 5, 2, 20, 15, 30', 'Concurso', '2002-02-20', NULL, 11, ''),
(44, 1, 'FÃ¡cil', 'Considere o seguinte programa escrito em C: ', 'O que serÃ¡ impresso quando o programa for executado?\r\n\r\n(a) foi muito facil\r\n\r\n(b) facil\r\n\r\n(c) muito facil\r\n\r\n(d) uito facil\r\n\r\n(e) acil', '(c) muito facil', 'Poscomp', '2009-11-12', '/var/www/trabalho_progweb/misc/imagens/questao/facil20141115150343248514584.png', 11, 'Uma imagem de um cÃ³digo-fonte na linguagem C.'),
(45, 3, 'MÃ©dia', 'Dada uma rede de interconexÃ£o estÃ¡tica com topologia hipercÃºbica de dimensÃ£o seis, com 64 nÃ³s, considere as afirmativas a seguir: \r\n\r\nI - Os nÃ³s com numeraÃ§Ã£o binÃ¡ria igual a 010101 e 101010 sÃ£o vizinhos.\r\nII - SÃ£o necessÃ¡rios 192 canais (links) para a construÃ§Ã£o desta rede.\r\nIII - Existem 5 nÃ³s conectados diretamente ao nÃ³ 111000. \r\nIV - O maior caminho mÃ­nimo entre dois nÃ³s da rede Ã© igual a 6.\r\nV - Se cada canal (link) da rede tem taxa de transmissÃ£o de 100 Mb/s, a largura de banda da bisseÃ§Ã£o Ã© igual a 3,2 Gb/s. ', 'Assinale a alternativa CORRETA:\r\n(a) Apenas a afirmativa IV estÃ¡ correta\r\n\r\n(b) Apenas as afirmativas III e IV estÃ£o corretas\r\n\r\n(c) Apenas as afirmativas I e V estÃ£o corretas\r\n\r\n(d) Apenas as afirmativas II, IV e V estÃ£o corretas.\r\n\r\n(e) Todas as afirmativas estÃ£o corretas. ', '(d) Apenas as afirmativas II, IV e V estÃ£o corretas.', 'Concurso', '2002-09-10', NULL, 11, ''),
(46, 10, 'DifÃ­cil', 'Considere uma arquitetura de memÃ³ria com as seguintes caracterÃ­sticas:\r\n- MemÃ³ria logicamente particionada em segmentos paginados.\r\n- EndereÃ§os virtuais de 32 bits:\r\n         - 8 para segmentos\r\n         - 11 para pÃ¡ginas\r\n         - O restante para o endereÃ§amento na pÃ¡gina\r\n- EndereÃ§os fÃ­sicos de 20 bits e pÃ¡ginas de 8KB; ', 'Caso o particionamento lÃ³gico fosse o de paginaÃ§Ã£o pura, a relaÃ§Ã£o entre o nÃºmero de pÃ¡ginas virtuais e o nÃºmero de frames seria equivalente a: \r\n\r\n(a) 8192\r\n\r\n(b) 4096\r\n\r\n(c) 1024\r\n\r\n(d) 128\r\n\r\n(e) 32 ', '(b) 4096', 'AcadÃªmica', '2009-10-12', NULL, 11, ''),
(47, 1, 'FÃ¡cil', 'Considere uma Ã¡rvore binÃ¡ria de busca T com n nÃ³s e altura h. A altura de uma Ã¡rvore Ã© o nÃºmero mÃ¡ximo de nÃ³s de um caminho entre a raiz e as folhas. Analise as afirmativas a seguir (a base logarÃ­tmica considerada Ã© 2): \r\n\r\nI - h < 1 + log n;\r\nII - Todo nÃ³ que pertence Ã  subÃ¡rvore esquerda de um nÃ³ x tem valor maior que o pai de x.\r\nIII - Uma busca em ordem simÃ©trica (in-order) em T produz uma ordenaÃ§Ã£o crescente dos elementos de T. \r\n\r\n', 'Assinale a alternativa\r\nCORRETA:\r\n(a) Apenas a afirmativa I estÃ¡ correta\r\n\r\n(b) Apenas a afirmativa II estÃ¡ correta\r\n\r\n(c) Apenas a afirmativa III estÃ¡ correta\r\n\r\n(d) Apenas as afirmativas I e II estÃ£o corretas\r\n\r\n(e) Apenas as afirmativas I e III estÃ£o corretas', '(c) Apenas a afirmativa III estÃ¡ correta', 'Poscomp', '2009-10-12', NULL, 11, ''),
(48, 1, 'FÃ¡cil', 'A funÃ§Ã£o PASCAL-like abaixo deve implementar o algoritmo de busca binÃ¡ria num vetor de inteiros A, com N elementos, ordenado crescentemente, onde o argumento\r\nv Ã© a chave de busca. ', 'Para que isso ocorra, o trecho pontilhado no corpo da funÃ§Ã£o deve ser substituÃ­do por: \r\n\r\n(a) (v=A[x]) or (e>d)\r\n\r\n(b) (v=A[x]) and (e>d)\r\n\r\n(c) (v=A[x])\r\n\r\n(d) (e>d)\r\n\r\n(e) not ((v=A[x]) or (e>d))', '(a) (v=A[x]) or (e>d)', 'Concurso', '2009-10-12', '/var/www/trabalho_progweb/misc/imagens/questao/pascallike20141115151628492975111.png', 1, 'Uma imagem de um cÃ³digo equivalente ao da linguagem Pascal.'),
(49, 1, 'FÃ¡cil', 'Percorrendo a Ã¡rvore binÃ¡ria a seguir em prÃ©-ordem, obtemos que seqÃ¼Ãªncia de caracteres? ', '(a) A C G F B E D\r\n\r\n(b) G C F A E B D\r\n\r\n(c) A B C D E F G\r\n\r\n(d) D B E A F C G\r\n\r\n(e) A B D E C F G ', '(e) A B D E C F G ', 'AcadÃªmica', '2009-10-12', '/var/www/trabalho_progweb/misc/imagens/questao/preorder20141115151915835199743.png', 1, 'Uma imagem de uma Ã¡rvore.'),
(50, 9, 'MÃ©dia', 'Seja o alfabeto {a, b} e a linguagem regular mostrada a seguir: ', 'Qual das expressÃµes regulares abaixo gera essa linguagem?\r\n\r\n(a) (a b* a b*)*\r\n\r\n(b) ( ( a a )* | b* )*\r\n\r\n(c) ( b* | ( a a )* | b* )*\r\n\r\n(d) ( b* a b* a b* )*\r\n\r\n(e) ( a a | b )* ', '(d) ( b* a b* a b* )*', 'Poscomp', '0000-00-00', '/var/www/trabalho_progweb/misc/imagens/questao/lfa2201411151522111992276763.png', 1, 'Uma imagem identificando uma linguagem.'),
(51, 7, 'MÃ©dia', 'Considere o circuito digital abaixo:\r\n ', 'Qual o valor de Q?\r\n\r\n(a) A+BC\r\n\r\n(b) B(A+B+C)\r\n\r\n(c) C(A+B)\r\n\r\n(d) A(B+C)\r\n\r\n(e) B(A+C)', '(e) B(A+C)', 'AcadÃªmica', '2009-10-12', '/var/www/trabalho_progweb/misc/imagens/questao/circuito20141115152535799124698.png', 1, 'Uma imagem que mostra um circuito.'),
(52, 9, 'MÃ©dia', 'Assinale a alternativa FALSA:\r\n', '(a) O conjunto de todas as MÃ¡quinas de Turing Ã© enumerÃ¡vel\r\n\r\n(b) O conjunto de todas as ExpressÃµes Regulares Ã© enumerÃ¡vel\r\n\r\n(c) Toda Linguagem Regular Ã© enumerÃ¡vel\r\n\r\n(d) Todo Conjunto Finito Ã© enumerÃ¡vel\r\n\r\n(e) Nenhum Conjunto Infinito Ã© enumerÃ¡vel', '(e) Nenhum Conjunto Infinito Ã© enumerÃ¡vel', 'AcadÃªmica', '2009-10-12', NULL, 1, ''),
(53, 9, 'DifÃ­cil', 'Considere o autÃ´mato finito nÃ£o-determinÃ­stico a seguir, sendo A o estado inicial e D o Ãºnico estado de aceitaÃ§Ã£o. ', 'Que autÃ´mato finito determinÃ­stico com d como sua funÃ§Ã£o de transiÃ§Ã£o de estado aceita a mesma linguagem? \r\n\r\n(a) Estado Inicial A, estados de aceitaÃ§Ã£o C e D - d(A, b) = B, d(B, a) = C, d(C, a) = D \r\n\r\n(b) Estado Inicial A, estado de aceitaÃ§Ã£o C - d(A, b) = B, d(B, a) = C, d(C, a) = C \r\n\r\n(c) Estado Inicial A, estado de aceitaÃ§Ã£o D - d(A, b) = B, d(B, a) = D, d(B, b) = C, d(C, a) = D \r\n\r\n(d) Todas as respostas acima estÃ£o corretas\r\n\r\n(e) Ã‰ impossÃ­vel converter esse autÃ´mato finito nÃ£o determinÃ­stico em um autÃ´mato finito determinÃ­stico. ', '(a) Estado Inicial A, estados de aceitaÃ§Ã£o C e D - d(A, b) = B, d(B, a) = C, d(C, a) = D ', 'Poscomp', '2009-10-12', '/var/www/trabalho_progweb/misc/imagens/questao/automaton201411151531171547511388.png', 1, 'Uma imagem que identifica um autÃ´mato.'),
(54, 7, 'MÃ©dia', 'Seja o circuito multiplexador da figura a seguir: ', 'Considere a seguintes afirmativas:\r\n\r\nI - Se S1=0 e S2=0, entÃ£o X terÃ¡ sempre o mesmo valor que D1.\r\nII - Se S1=0 e S2=1, entÃ£o X terÃ¡ sempre o mesmo valor que D2.\r\nIII - Se S1=1 e S2=1, entÃ£o X terÃ¡ sempre o mesmo valor que D0.\r\n\r\nAssinale a alternativa CORRETA:\r\n\r\n(a) Apenas a afirmativa I estÃ¡ correta\r\n\r\n(b) Apenas a afirmativa II estÃ¡ correta\r\n\r\n(c) Apenas a afirmativa III estÃ¡ correta\r\n\r\n(d) Apenas as afirmativas I e II estÃ£o corretas\r\n\r\n(e) Apenas as afirmativas I e III estÃ£o corretas', '(e) Apenas as afirmativas I e III estÃ£o corretas', 'Concurso', '2002-09-10', '/var/www/trabalho_progweb/misc/imagens/questao/mult201411151533512054361643.png', 1, 'Uma imagem que identifica um circuito multiplexador.'),
(55, 3, 'MÃ©dia', 'Em relaÃ§Ã£o Ã  arquitetura cliente/servidor, usada na implementaÃ§Ã£o de sistemas distribuÃ­dos, analise as seguintes afirmativas: \r\n\r\nI - A arquitetura cliente/servidor define um modelo de interaÃ§Ã£o entre processos clientes e servidores que resolve o problema do rendezvous: clientes iniciam a\r\ncomunicaÃ§Ã£o e servidores esperam por requisiÃ§Ãµes.\r\nII - Em servidores sem estado (informaÃ§Ãµes de estado nÃ£o sÃ£o mantidas entre o processamento de requisiÃ§Ãµes), o significado de uma mensagem do cliente nÃ£o deve depender da sequÃªncia de mensagens anteriores.\r\nIII - Um programa cliente individual opera como um programa convencional, ele nÃ£o precisa gerenciar concorrÃªncia explicitamente na comunicaÃ§Ã£o com o servidor. ', 'Assinale a alternativa\r\nCORRETA:\r\n\r\n(a) Apenas a afirmativa I Ã© verdadeira\r\n\r\n(b) Apenas a afirmativa II Ã© verdadeira\r\n\r\n(c) Apenas a afirmativa III Ã© verdadeira\r\n\r\n(d) Apenas as afirmativas I e II sÃ£o verdadeiras\r\n\r\n(e) Todas as afirmativas sÃ£o verdadeiras ', '(e) Todas as afirmativas sÃ£o verdadeiras ', 'AcadÃªmica', '2009-11-12', NULL, 1, ''),
(56, 9, 'FÃ¡cil', 'A anÃ¡lise lÃ©xica Ã© usualmente implementada a partir de:\r\n\r\n', '(a) GramÃ¡tica regular\r\n\r\n(b) GramÃ¡tica livre de contexto\r\n\r\n(c) GramÃ¡tica sensÃ­vel ao contexto\r\n\r\n(d) GramÃ¡tica irrestrita\r\n\r\n(e) GramÃ¡tica de pilha ', '(a) GramÃ¡tica regular', 'Concurso', '2009-10-12', NULL, 1, ''),
(57, 3, 'DifÃ­cil', 'Os mecanismos de controle de congestionamento e controle de fluxo desempenham um papel fundamental no projeto de uma rede de computadores. Considere as\r\nafirmativas a seguir sobre os dois mecanismos. \r\n\r\nI - O mecanismo de controle de congestionamento regula (ou seja, aumenta e diminui dinamicamente) a taxa com a qual o transmissor envia dados pela rede.\r\nII - O mecanismo de controle de congestionamento garante que o receptor irÃ¡ receber todos os dados enviados pelo transmissor.\r\nIII - O mecanismo de controle de fluxo regula (ou seja, aumenta e diminui dinamicamente) a taxa com a qual o transmissor envia dados pela rede.\r\nIV - O mecanismo de controle de fluxo garante que o receptor irÃ¡ receber todos os dados enviados pelo transmissor. ', 'Assinale a alternativa CORRETA:\r\n\r\n(a) Apenas as alternativas I, II e III sÃ£o verdadeiras\r\n\r\n(b) Apenas as alternativas I e III sÃ£o verdadeiras\r\n\r\n(c) Apenas as alternativas II e IV sÃ£o verdadeiras\r\n\r\n(d) Apenas as alternativas II I e IV sÃ£o verdadeiras\r\n\r\n(e) Todas as alternativas sÃ£o verdadeiras', '(b) Apenas as alternativas I e III sÃ£o verdadeiras', 'Poscomp', '2009-10-12', NULL, 1, ''),
(58, 3, 'FÃ¡cil', 'Um dos problemas importantes na Internet Ã© o endereÃ§amento de processos, ou seja, aplicaÃ§Ãµes em execuÃ§Ã£o em um determinado computador. \r\nConsidere as afirmativas a seguir.\r\n\r\nI - Todo pacote transmitido precisa conter o endereÃ§o IP e a porta do processo destino.\r\nII - Pacotes do protocolo TCP nÃ£o precisam conter o endereÃ§o IP nem a porta do processo do transmissor.\r\nIII - A tupla endereÃ§o IP de origem e destino e porta de origem e destino identificam unicamente uma conexÃ£o TCP.\r\nIV - Um processo que utiliza o protocolo UDP para se comunicar nunca recebe pacotes fora da ordem em que foram transmitidos. ', 'Assinale a alternativa CORRETA:\r\n\r\n(a) Apenas as alternativas I e II sÃ£o verdadeiras\r\n\r\n(b) Apenas as alternativas II e III sÃ£o verdadeiras\r\n\r\n(c) Apenas as alternativas I e III sÃ£o verdadeiras\r\n\r\n(d) Apenas as alternativas I, III e IV sÃ£o verdadeiras\r\n\r\n(e) Todas as alternativas sÃ£o verdadeiras', '(c) Apenas as alternativas I e III sÃ£o verdadeiras', 'AcadÃªmica', '2009-10-12', NULL, 1, ''),
(59, 8, 'MÃ©dia', 'Considere as seguintes expressÃµes booleanas:', 'Considere ainda as seguintes afirmaÃ§Ãµes:\r\n\r\nI - A Ã© equivalente a B.\r\nII - C Ã© equivalente a D.\r\nIII - A Ã© equivalente a D.\r\nIV - B Ã© equivalente a C.\r\n\r\nQuais das alternativas acima sÃ£o verdadeiras?\r\n\r\n(a) Somente as afirmaÃ§Ãµes I e II sÃ£o verdadeiras\r\n\r\n(b) Somente as afirmaÃ§Ãµes I e III sÃ£o verdadeiras\r\n\r\n(c) Somente as afirmaÃ§Ãµes II e IV sÃ£o verdadeiras\r\n\r\n(d) Todas as afirmaÃ§Ãµes sÃ£o verdadeiras\r\n\r\n(e) Todas as afirmaÃ§Ãµes sÃ£o falsas', '(a) Somente as afirmaÃ§Ãµes I e II sÃ£o verdadeiras', 'Poscomp', '2005-09-10', '/var/www/trabalho_progweb/misc/imagens/questao/bool201411151551041180931120.png', 1, ''),
(60, 3, 'FÃ¡cil', 'Os protocolos de transporte atribuem a cada serviÃ§o um identifcador Ãºnico, o qual Ã© empregado para encaminhar uma requisiÃ§Ã£o de um aplicativo cliente ao processo\r\nservidor correto. Nos protocolos de transporte TCP e UDP, como esse identifcador se denomina?', '(a) EndereÃ§o IP\r\n\r\n(b) Porta \r\n\r\n(c) ConexÃ£o \r\n\r\n(d) Identificador do processo (PID)\r\n\r\n(e) Protocolo de aplicaÃ§Ã£o', '(b) Porta ', 'Poscomp', '2005-09-10', NULL, 1, ''),
(61, 7, 'DifÃ­cil', 'Dado a imagem abaixo, analise as seguintes afirmativas:', 'I - O circuito mostrado Ã© um circuito seqÃ¼encial.\r\nII - O circuito mostrado Ã© um circuito combinacional.\r\nIII - O circuito mostrado implementa uma mÃ¡quina de Mealy de quatro estados.\r\nIV - O circuito mostrado implementa uma mÃ¡quina de Moore de quatro estados.\r\n\r\nA anÃ¡lise permite concluir que\r\n\r\n(a) Somente as afirmativas I e II sÃ£o verdadeiras\r\n\r\n(b) Somente a afirmativa III Ã© verdadeira\r\n\r\n(c) Somente a afirmativa IV Ã© verdadeira\r\n\r\n(d) Somente a afirmativa I Ã© verdadeira\r\n\r\n(e) Somente a afirmativa II Ã© verdadeira', '(e) Somente a afirmativa II Ã© verdadeira', 'Poscomp', '2007-09-10', '/var/www/trabalho_progweb/misc/imagens/questao/sd20141115160622620266412.png', 11, 'Uma imagem identificando um circuito digital.'),
(63, 9, 'MÃ©dia', 'Assinale a alternativa que apresenta a afirmativa FALSA.', '(a) Uma linguagem L Ã© aceita por uma MÃ¡quina de Turing nÃ£o determinÃ­stica com k fitas, m dimensÃµes, n\r\ncabeÃ§otes de leitura e gravaÃ§Ã£o por fita se, e somente se, ela Ã© aceita por uma MÃ¡quina de Turing determinÃ­stica com uma fita infinita em apenas um sentido e um cabeÃ§ote de leitura e gravaÃ§Ã£o\r\n(b) Um problema Ã© dito ser decidÃ­vel se a linguagem associada a esse problema Ã© recursiva\r\n(c) O conjunto de todos os programas que param para uma dada entrada Ã© um conjunto recursivo mas nÃ£o um conjunto recursivamente enumerÃ¡vel\r\n(d) Uma funÃ§Ã£o Ã© parcialmente computÃ¡vel se, e somente se, ela pode ser obtida a partir de funÃ§Ãµes iniciais (por exemplo, sucessor, zero e projeÃ§Ã£o) por um nÃºmero finito de aplicaÃ§Ãµes de composiÃ§Ã£o, recursÃ£o primitiva e minimalizaÃ§Ã£o\r\n(e) Uma MÃ¡quina Universal de Turing U toma como argumentos uma descriÃ§Ã£o de uma MÃ¡quina de Turing M qualquer e uma entrada x para M, e executa as mesma operaÃ§Ãµes sobre x que seriam executadas por M', '(c) O conjunto de todos os programas que param para uma dada entrada Ã© um conjunto recursivo mas nÃ£o um conjunto recursivamente enumerÃ¡vel', 'Poscomp', '2007-09-10', NULL, 12, ''),
(64, 4, 'DifÃ­cil', 'Suponha que tenhamos Ã  nossa disposiÃ§Ã£o um algoritmo MULT que efetua a multiplicaÃ§Ã£o de duas matrizes A (p x q) e B (q x r) dadas como entrada com p x q x r multiplicaÃ§Ãµes de escalares. Esse algoritmo Ã©, entÃ£o, usado para definir o seguinte problema de decisÃ£o chamado MULTMAT:\r\n\r\nENTRADA: vetor p[0], p[1], ..., p[n], um inteiro positivo m.\r\nQUESTÃƒO: existe uma sequÃªncia de multiplicaÃ§Ãµes de duas matrizes com o algoritmo MULT que produz o resultado de A1 A2 ... An, em que cada Ai, para todo i âˆˆ {1, 2, ..., n}, Ã© uma matriz  de dimensÃµes p[i-1] x p[i], com m multiplicaÃ§Ãµes escalares no mÃ¡ximo?\r\n\r\nConsidere as seguintes afirmativas na imagem abaixo.', 'Assinale a alternativa que apresenta a(s) afirmativa(s) CORRETA(S):\r\n\r\n(a) Somente a afirmativa I\r\n\r\n(b) Somente a afirmativa II\r\n\r\n(c) Somente a afirmativa III\r\n\r\n(d) Somente as afirmativas II e III\r\n\r\n(e) Somente as afirmativas I, II e III', '(b) Somente a afirmativa II', 'Poscomp', '2007-09-10', '/var/www/trabalho_progweb/misc/imagens/questao/multmat201411161217351453542797.png', 12, 'Uma imagem que identifica trÃªs afirmativas a respeito do algoritmo MULTMAT.'),
(65, 1, 'MÃ©dia', 'Analise as seguintes afirmativas:\r\n\r\nI - Encapsulamento Ã© a capacidade de uma operaÃ§Ã£o atuar em modos diversos em classes diferentes.\r\n\r\nII - Polimorfismo Ã© o compartilhamento de atributos e mÃ©todos entre classes com base em um relacionamento hierÃ¡rquico.\r\n\r\nIII - HeranÃ§a consiste no processo de ocultaÃ§Ã£o dos detalhes internos de implementaÃ§Ã£o de um objeto.\r\n\r\nIV - SobreposiÃ§Ã£o Ã© a redefinÃ§Ã£o das funÃ§Ãµes de um mÃ©todo herdado. Os mÃ©todos apresentam assinaturas iguais.\r\n\r\nV - Em JAVA, todos os mÃ©todos numa classe abstrata devem ser declarados como abstratos.', 'A partir da anÃ¡lise, pode-se concluir que:\r\n\r\n(a) Apenas a afirmativa IV estÃ¡ correta\r\n\r\n(b) Apenas as afirmativas III e IV estÃ£o corretas\r\n\r\n(c) Apenas as afirmativas I, IV e V estÃ£o corretas\r\n\r\n(d) Apenas as afirmativas I, III e V estÃ£o corretas \r\n\r\n(e) Todas as afirmativas sÃ£o falsas\r\n\r\n', '(a) Apenas a afirmativa IV estÃ¡ correta', 'AcadÃªmica', '2007-09-10', NULL, 12, 'NÃ£o hÃ¡ imagem.'),
(66, 4, 'DifÃ­cil', 'Observe as funÃ§Ãµes representadas no grÃ¡fico abaixo:', 'Assinale a afirmativa FALSA sobre o crescimento assintÃ³tico dessas funÃ§Ãµes.\r\n\r\n(a) f(n) = O(h(n)) e i(n) = â„¦(g(n))\r\n\r\n(b) f(n) = Î˜(h(n)) e i(n) = â„¦(h(n))\r\n\r\n(c) g(n) = O(i(n)) e h(n) = â„¦(g(n))\r\n\r\n(d) g(n) = O(i(n)), i(n) = O(f(n)) e, portanto, g(n) = O(f(n))\r\n\r\n(e) h(n) = â„¦(i(n)), logo, i(n) = O(h(n))', '(b) f(n) = Î˜(h(n)) e i(n) = â„¦(h(n))', 'AcadÃªmica', '2007-09-10', '/var/www/trabalho_progweb/misc/imagens/questao/analise_grafico20141116132449533778379.png', 12, 'Uma imagem identificando um grÃ¡fico com o crescimento assintÃ³tico de algumas funÃ§Ãµes.'),
(68, 1, 'DifÃ­cil', '28) Com base nos conhecimentos sobre as linguagens de programaÃ§Ã£o funcionais, considere as afirmativas a seguir:\r\n\r\nI -  Uma linguagem de programaÃ§Ã£o funcional tem o objetivo de imitar as funÃ§Ãµes matemÃ¡ticas, ou seja, os programas sÃ£o definiÃ§Ãµes de funÃ§Ãµes e de especificaÃ§Ãµes da aplicaÃ§Ã£o dessas funÃ§Ãµes.\r\n\r\nII -  Nas linguagens funcionais, os dados e as rotinas para manipulÃ¡-los sÃ£o mantidos em uma mesma unidade, chamada objeto. Os dados sÃ³ podem ser manipulados por meio das rotinas que estÃ£o na mesma unidade.\r\n\r\nIII -  As rotinas de um programa do paradigma funcional descrevem aÃ§Ãµes que mudam o estado das variÃ¡veis do programa, seguindo uma sequÃªncia de comandos para o computador executar.', 'Assinale a alternativa correta:\r\n\r\n(a) Somente as afirmativas I e IV sÃ£o corretas\r\n\r\n(b) Somente as afirmativas II e III sÃ£o corretas\r\n\r\n(c) Somente as afirmativas III e IV sÃ£o corretas\r\n\r\n(d) Somente as afirmativas I, II e III sÃ£o corretas\r\n\r\n(e) Somente as afirmativas I, II e IV sÃ£o corretas', '(a) Somente as afirmativas I e IV sÃ£o corretas', 'Poscomp', '2010-09-09', NULL, 12, ''),
(69, 1, 'MÃ©dia', 'No programa apresentado abaixo, a tÃ©cnica da recursividade foi aplicada Ã s trÃªs funÃ§Ãµes F1, F2 e F3. Essa tÃ©cnica envolve a definiÃ§Ã£o de uma funÃ§Ã£o ou rotina que pode invocar a si prÃ³pria. Com relaÃ§Ã£o ao programa apresentado e Ã  tÃ©cnica de recursÃ£o, atribua F (falso) ou V (verdadeiro) para as afirmativas a seguir.', 'I - A chamada da funÃ§Ã£o F1, atravÃ©s da expressÃ£o F1(X,Y), pode ser substituÃ­da, sem alterar o resultado do programa, pela expressÃ£o X%Y.\r\nII -  O objetivo da funÃ§Ã£o F2 Ã© retornar o valor da variÃ¡vel X elevado Ã  Y-Ã©sima potÃªncia.\r\nIII -  A chamada Ã  funÃ§Ã£o F3 entrarÃ¡ em uma recursÃ£o sem fim se o valor da variÃ¡vel X for maior que o valor da variÃ¡vel Y.\r\nIV -  A funÃ§Ã£o main nÃ£o Ã© recursiva, pois na Linguagem C nÃ£o Ã© possÃ­vel implementar esta tÃ©cnica na funÃ§Ã£o principal do programa.\r\nV -  A expressÃ£o ((A > 0) && (A < 1000) && (B > 1) && (B < 10)), da funÃ§Ã£o main, pode ser substituÃ­da pela expressÃ£o (!((A <= 0) || (A >= 1000) || (B <= 1) || (B >= 10))), sem afetar o resultado do comando condicional\r\nif nesta expressÃ£o.\r\nAssinale a alternativa que contÃ©m, de cima para baixo, a sequÃªncia correta.\r\n(a) F, V, F, F, V\r\n\r\n(b) V, F, F, V, F\r\n\r\n(c) V, V, F, V, V\r\n\r\n(d) F, V, V, V, F\r\n\r\n(e) V, F, F, F, V', '(e) V, F, F, F, V', 'Concurso', '2010-09-09', '/var/www/trabalho_progweb/misc/imagens/questao/progc20141116162644274132377.png', 12, 'Uma imagem identificando um cÃ³digo escrito em C.'),
(70, 7, 'MÃ©dia', ' Considere o diagrama a seguir:', 'Seja a mÃ¡quina de estados finitos representada pelo diagrama acima, determine o modelo (Mealy ou Moore) e o circuito digital ao qual ela corresponde:\r\n\r\n(a) Modelo de Mealy correspondente a um contador mÃ³dulo 5\r\n\r\n(b) Modelo de Moore correspondente a um contador mÃ³dulo 5\r\n\r\n(c) Modelo de Mealy correspondente a um identificador da sequÃªncia 100\r\n\r\n(d) Modelo de Moore correspondente a um identificador da sequÃªncia 100\r\n\r\n(e) Modelo de Mealy correspondente a um flip-flop JK', '(a) Modelo de Mealy correspondente a um contador mÃ³dulo 5', 'Poscomp', '2010-09-09', '/var/www/trabalho_progweb/misc/imagens/questao/diagram20141116163023844084311.png', 12, 'Imagem identificando um diagrama de mÃ¡quina de estados.');

-- --------------------------------------------------------

--
-- Table structure for table `Usuario`
--

CREATE TABLE IF NOT EXISTS `Usuario` (
  `u_id` int(11) NOT NULL AUTO_INCREMENT,
  `login` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `senha` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`u_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=13 ;

--
-- Dumping data for table `Usuario`
--

INSERT INTO `Usuario` (`u_id`, `login`, `senha`) VALUES
(1, 'diego', '3ba558c4435917c0e60e8a4a99a38d96'),
(4, 'ricardo', 'dbc4d84bfcfe2284ba11beffb853a8c4'),
(6, 'roberto', 'dbc4d84bfcfe2284ba11beffb853a8c4'),
(11, 'nicolas', 'c5fe25896e49ddfe996db7508cf00534'),
(12, 'rodolfo', 'b6d767d2f8ed5d21a44b0e5886680cb9');

--
-- Constraints for dumped tables
--

--
-- Constraints for table `Questao`
--
ALTER TABLE `Questao`
  ADD CONSTRAINT `deletar` FOREIGN KEY (`u_id`) REFERENCES `Usuario` (`u_id`) ON DELETE CASCADE,
  ADD CONSTRAINT `Questao_ibfk_1` FOREIGN KEY (`m_id`) REFERENCES `Materia` (`m_id`),
  ADD CONSTRAINT `Questao_ibfk_2` FOREIGN KEY (`u_id`) REFERENCES `Usuario` (`u_id`),
  ADD CONSTRAINT `Questao_ibfk_3` FOREIGN KEY (`u_id`) REFERENCES `Usuario` (`u_id`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
