/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dirija;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Calendar;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author nicolas
 */
public class UIAluguelVeiculo extends javax.swing.JFrame {

    /* Definimos os objetos como atributos da classe */
    private AluguelVeiculoController v = new AluguelVeiculoController();
    private String[][] clientes = v.consultarClientes();
    private String[][] veiculos = null;
    private String[][] estabelecimentos = v.consultarEstabelecimentos();
    // Variáveis globais para o método "finalizarAluguel"
    private Cliente cli = null;
    private Veiculo veiculo = null;
    private String localRetirada = null;
    private String estabDevolucao = null;
    private String dRetirada = null;
    private String dDevolucao = null;
    private byte formaPagamento = 0;
    private float total;
    
    /**
     * Creates new form UIAluguelVeiculo
     */
    public UIAluguelVeiculo() {
        initComponents();
        localRetirada = v.informarLocalRetirada();
        estabelecimentoRetirada.setText(localRetirada);
        String data = v.informarDataAtual();
        dataRetirada.setText(data);
        dRetirada = data;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parcelas = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        valorParcelas = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        consultarClientes = new javax.swing.JButton();
        clientName = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();
        reservar = new javax.swing.JButton();
        consultarVeiculos = new javax.swing.JButton();
        modeloVeiculo = new javax.swing.JTextField();
        situacao = new javax.swing.JTextField();
        consultarEstabelecimento = new javax.swing.JButton();
        estabelecimentoDevolucao = new javax.swing.JTextField();
        estabelecimentoRetirada = new javax.swing.JTextField();
        dataRetirada = new javax.swing.JTextField();
        dataDevolucao = new javax.swing.JTextField();
        valorTotal = new javax.swing.JTextField();
        formaPgto = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("Número de Parcelas");

        jLabel3.setText("Valor das Parcelas");

        valorParcelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorParcelasActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Parcelas", "2", "3", "4", "5", "6" }));
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel4.setText("                             Pagamento à Prazo");

        javax.swing.GroupLayout parcelasLayout = new javax.swing.GroupLayout(parcelas.getContentPane());
        parcelas.getContentPane().setLayout(parcelasLayout);
        parcelasLayout.setHorizontalGroup(
            parcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parcelasLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(parcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(parcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valorParcelas))
                .addContainerGap(27, Short.MAX_VALUE))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        parcelasLayout.setVerticalGroup(
            parcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parcelasLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(33, 33, 33)
                .addGroup(parcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(parcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(valorParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setText("                                                                                                                                       Aluguel de Veículo");

        consultarClientes.setText("Consultar Clientes");
        consultarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarClientesActionPerformed(evt);
            }
        });

        clientName.setEditable(false);
        clientName.setText("Nome do Cliente");

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        reservar.setText("Alugar");
        reservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservarActionPerformed(evt);
            }
        });

        consultarVeiculos.setText("Consultar Veículos Disponíveis");
        consultarVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarVeiculosActionPerformed(evt);
            }
        });

        modeloVeiculo.setEditable(false);
        modeloVeiculo.setText("Modelo do Veículo");

        situacao.setEditable(false);
        situacao.setText("Em andamento");

        consultarEstabelecimento.setText("Consultar Estabelecimento");
        consultarEstabelecimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarEstabelecimentoActionPerformed(evt);
            }
        });

        estabelecimentoDevolucao.setEditable(false);
        estabelecimentoDevolucao.setText("Estabelecimento de Devolução");

        estabelecimentoRetirada.setEditable(false);
        estabelecimentoRetirada.setText("Estabelecimento de Retirada");
        estabelecimentoRetirada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estabelecimentoRetiradaActionPerformed(evt);
            }
        });

        dataRetirada.setEditable(false);
        dataRetirada.setText("Data de Retirada");
        dataRetirada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataRetiradaActionPerformed(evt);
            }
        });

        dataDevolucao.setText("Data de Devolução");
        dataDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataDevolucaoActionPerformed(evt);
            }
        });

        valorTotal.setEditable(false);
        valorTotal.setText("Valor Total");

        formaPgto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma opção", "à Vista", "à Prazo" }));
        formaPgto.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                formaPgtoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel1.setText("                                                                                   Sistema de Aluguel de Veículos Dirija - Created by Diego Cintra et al");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estabelecimentoRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formaPgto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(clientName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(consultarClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(situacao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dataDevolucao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modeloVeiculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estabelecimentoDevolucao, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(consultarEstabelecimento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(consultarVeiculos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(reservar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(306, 306, 306))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(consultarClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(estabelecimentoRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(formaPgto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(consultarVeiculos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modeloVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(situacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(consultarEstabelecimento)
                        .addGap(12, 12, 12)
                        .addComponent(estabelecimentoDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(valorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarClientesActionPerformed
        String[] info = new String[clientes[1].length];
        System.out.print(clientes[1].length);
        for(int i = 0; i < info.length; i++)
        {
            info[i] = "Nome: " + clientes[1][i] + " CPF: " + clientes[0][i];
        }
        final UIList lista = new UIList(info);
        lista.setVisible(true);
        lista.list.addMouseListener(new MouseAdapter()
        {
            @Override
            public void mouseClicked(MouseEvent evt) 
            {
                lista.list = (JList)evt.getSource();
                Rectangle r = lista.list.getCellBounds(0, lista.list.getLastVisibleIndex());
                if(evt.getClickCount() == 2 && r != null & r.contains(evt.getPoint()))
                {
                    int index = lista.list.locationToIndex(evt.getPoint());
                    cli = new Cliente(clientes[1][index], clientes[0][index], new Integer((clientes[4][index])),
                    clientes[5][index], clientes[6][index], clientes[7][index], clientes[11][index],
                    clientes[12][index], clientes[13][index]);
                    lista.setVisible(false);
                    int sinal = v.verificarPendencia(cli);
                    if(sinal != 0)
                    {
                        JOptionPane.showMessageDialog(lista, v.gerarMensagem(sinal));
                        dispose();
                    }
                    else
                    {
                        clientName.setText(cli.getNome());
                    }
                }
            }
        });
    }//GEN-LAST:event_consultarClientesActionPerformed

    private void consultarVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarVeiculosActionPerformed
        if(cli == null)
        {
            JOptionPane.showMessageDialog(this, "Obrigatória a inserção do cliente.");
        }
        else
        {
            veiculos = v.consultarVeiculosLivres(cli);
            if(veiculos == null)
            {
                JOptionPane.showMessageDialog(this, v.gerarMensagem(3));
                dispose();
            }
            else
            {
                String[] info = new String[veiculos[4].length];
                for(int i = 0; i < info.length; i++)
                {
                    info[i] = "Fabricante: " + veiculos[5][i] + " Modelo: " + veiculos[4][i] + " Chassi: " + veiculos[0][i]
                        + " Estado tanque: " + veiculos[7][i] + " Estado geral: " + veiculos[8][i];
                }
                final UIList lista = new UIList(info);
                lista.setVisible(true);
                lista.list.addMouseListener(new MouseAdapter()
                {
                    @Override
                    public void mouseClicked(MouseEvent evt) 
                    {
                        lista.list = (JList)evt.getSource();
                            Rectangle r = lista.list.getCellBounds(0, lista.list.getLastVisibleIndex());
                            if(evt.getClickCount() == 2 && r != null & r.contains(evt.getPoint()))
                            {
                                int index = lista.list.locationToIndex(evt.getPoint());
                                veiculo = new Veiculo(veiculos[3][index], veiculos[0][index], veiculos[2][index],
                                veiculos[4][index], veiculos[5][index], veiculos[6][index], veiculos[7][index],
                                veiculos[8][index], veiculos[9][index], new Float(veiculos[10][index]),
                                new Float(veiculos[11][index]));
                                lista.setVisible(false);
    //                            int sinal = v.verificarPendencia(veiculo, cli);
    //                            if(sinal != 0)
    //                            {
    //                                JOptionPane.showMessageDialog(lista, v.gerarMensagem(sinal));
    //                                dispose();
    //                            }
    //                            else
    //                            {
    //                                clientName.setText(cli.getNome());
    //                            }
                                modeloVeiculo.setText(veiculo.getModelo());           
                            }
                    }    
                });
            }
        }
    }//GEN-LAST:event_consultarVeiculosActionPerformed

    private void consultarEstabelecimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarEstabelecimentoActionPerformed
        String[] info = new String[estabelecimentos[2].length];
        for(int i = 0; i < info.length; i++)
        {
            info[i] = "Cidade: " + estabelecimentos[2][i] + " Número de veículos: " + estabelecimentos[9][i];
        }
        final UIList lista = new UIList(info);
        lista.setVisible(true);
        lista.list.addMouseListener(new MouseAdapter()
        {
            @Override
            public void mouseClicked(MouseEvent evt) 
            {
                lista.list = (JList)evt.getSource();
                Rectangle r = lista.list.getCellBounds(0, lista.list.getLastVisibleIndex());
                if(evt.getClickCount() == 2 && r != null & r.contains(evt.getPoint()))
                {
                    int index = lista.list.locationToIndex(evt.getPoint());
//                    Estabelecimento estabelecimento = new Estabelecimento(new Integer((estabelecimentos[1][index])),
//                    estabelecimentos[0][index], estabelecimentos[4][index], estabelecimentos[5][index], 
//                    estabelecimentos[6][index], new Integer((estabelecimentos[7][index])), [11][index],
//                    new Integer ((clientes[12][index])), new Integer ((clientes[13][index])));
                    lista.setVisible(false);
                    estabDevolucao = estabelecimentos[2][index];
                    estabelecimentoDevolucao.setText("Dirija "+estabelecimentos[2][index]);
//                    String retirada = v.informarLocalRetirada();
//                    estabelecimentoRetirada.setText(retirada);
                }
            }
        });
    }//GEN-LAST:event_consultarEstabelecimentoActionPerformed

    private void estabelecimentoRetiradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estabelecimentoRetiradaActionPerformed
        localRetirada = v.informarLocalRetirada();
        estabelecimentoRetirada.setText(localRetirada);
    }//GEN-LAST:event_estabelecimentoRetiradaActionPerformed

    private void dataDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataDevolucaoActionPerformed
        dDevolucao = dataDevolucao.getText();
        int sinal = v.verificarData(dRetirada, dDevolucao, veiculo);
        if(sinal != 0)
        {
            JOptionPane.showMessageDialog(this, v.gerarMensagem(sinal));
        }
    }//GEN-LAST:event_dataDevolucaoActionPerformed

    private void formaPgtoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_formaPgtoPopupMenuWillBecomeInvisible
        if(veiculo == null || dRetirada == null || dDevolucao == null)
            JOptionPane.showMessageDialog(this, "Campos obrigatórios não preenchidos.");
        else
        {
            total = v.calcularValorTotal(veiculo, dRetirada, dDevolucao);
            valorTotal.setText(Float.toString(total));
            formaPagamento = 1;
            if(this.formaPgto.getSelectedItem() == "à Prazo")
            {
                parcelas.setVisible(true);
                parcelas.setSize(376,175);
            }
        }   
    }//GEN-LAST:event_formaPgtoPopupMenuWillBecomeInvisible

    private void dataRetiradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataRetiradaActionPerformed
//        dRetirada = dataRetirada.getText();
//        int sinal = v.verificarData(dRetirada, null, null);
//        if(sinal != 0)
//        {
//            JOptionPane.showMessageDialog(this, v.gerarMensagem(sinal));
//        }
    }//GEN-LAST:event_dataRetiradaActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void valorParcelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorParcelasActionPerformed
        
    }//GEN-LAST:event_valorParcelasActionPerformed

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
        float valorParcelamento;
        if(this.jComboBox1.getSelectedItem() == "2")
        {
            formaPagamento = 2;
            valorParcelamento = v.calcularValorPrazo(total, 2);
            String valor = Float.toString(valorParcelamento);
            this.valorParcelas.setText(valor);
        }
        else if(this.jComboBox1.getSelectedItem() == "3")
        {
            formaPagamento = 3;
            valorParcelamento = v.calcularValorPrazo(total, 3);
            String valor = Float.toString(valorParcelamento);
            this.valorParcelas.setText(valor);
        }
        else if(this.jComboBox1.getSelectedItem() == "4")
        {
            formaPagamento = 4;
            valorParcelamento = v.calcularValorPrazo(total, 4);
            String valor = Float.toString(valorParcelamento);
            this.valorParcelas.setText(valor);
        }
        else if(this.jComboBox1.getSelectedItem() == "5")
        {
            formaPagamento = 5;
            valorParcelamento = v.calcularValorPrazo(total, 5);
            String valor = Float.toString(valorParcelamento);
            this.valorParcelas.setText(valor);
        }
        else if(this.jComboBox1.getSelectedItem() == "6")
        {
            formaPagamento = 6;
            valorParcelamento = v.calcularValorPrazo(total, 6);
            String valor = Float.toString(valorParcelamento);
            this.valorParcelas.setText(valor);
        }
            
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    private void reservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservarActionPerformed
       if(cli != null && veiculo != null && localRetirada != null && estabDevolucao != null 
               && dRetirada != null && dDevolucao != null && formaPagamento != 0
               && total != 0.00f)
       {
           JOptionPane.showMessageDialog(this, 
           v.finalizarAluguel(cli, veiculo, localRetirada, estabDevolucao, dRetirada, dDevolucao, formaPagamento, total));
           dispose();
       }
       else
       {
           JOptionPane.showMessageDialog(this, "Campos obrigatórios não preenchidos.");
       }
    }//GEN-LAST:event_reservarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIAluguelVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIAluguelVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIAluguelVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIAluguelVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIAluguelVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField clientName;
    private javax.swing.JButton consultarClientes;
    private javax.swing.JButton consultarEstabelecimento;
    private javax.swing.JButton consultarVeiculos;
    private javax.swing.JTextField dataDevolucao;
    private javax.swing.JTextField dataRetirada;
    private javax.swing.JTextField estabelecimentoDevolucao;
    private javax.swing.JTextField estabelecimentoRetirada;
    private javax.swing.JComboBox formaPgto;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField modeloVeiculo;
    private javax.swing.JFrame parcelas;
    private javax.swing.JButton reservar;
    private javax.swing.JTextField situacao;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField valorParcelas;
    private javax.swing.JTextField valorTotal;
    // End of variables declaration//GEN-END:variables
}


